export enum ActionType {
    LOGIN,
    CHANGE_STORE_QUANTITY,
    SET_ITEM_ACTION,
    REMOVE_ITEM_FROM_CART,
    REMOVE_ALL_FROM_CART,
    BUY_ITEMS,
    ADD_COMMENT,
    SET_MY_WISH_LISTS,
    ADD_MY_WISH_LIST,
    DELETE_MY_WISH_LIST,
    UPDATE_MY_WISH_LIST,
    SET_OTHER_WISH_LISTS,
    SET_MANAGER_USERS,
    UPDATE_MANAGER_USER
}